# This file defines the desired state for your application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-deployment # The name of the deployment
spec:
  replicas: 3 # Run 3 pods (instances) of your application
  selector:
    matchLabels:
      app: aceest-fitness # This must match the pod labels below
  template:
    metadata:
      labels:
        app: aceest-fitness # The label for your pods
    spec:
      containers:
        - name: aceest-app-container
          # !! REPLACE 'your-dockerhub-username' !!
          image: nehabpandya/aceest-fitness:latest # The image to pull
          ports:
            - containerPort: 5000 # The port Flask is running on (from gunicorn)
